# docker-compose.yml
version: '2'

services:
  web:
    build:
    # build from Dockerfile
      context: ./
      dockerfile: Dockerfile
    ports:
     - "8080:8080"
    volumes:
     - .:/code
  # redis:
  #   image: redis